# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/timing_game/timing_game.cache/wt [current_project]
set_property parent.project_path Z:/timing_game/timing_game.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo z:/timing_game/timing_game.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet z:/timing_game/timing_game.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files z:/timing_game/timing_game.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_mem {
  Z:/timing_game/timing_game.srcs/sources_1/new/bg_palette.mem
  Z:/timing_game/timing_game.srcs/sources_1/new/bg.mem
  Z:/timing_game/timing_game.srcs/sources_1/new/stop_palette.mem
  Z:/timing_game/timing_game.srcs/sources_1/new/stop.mem
}
read_verilog -library xil_defaultlib {
  Z:/timing_game/timing_game.srcs/sources_1/new/vram.v
  Z:/timing_game/timing_game.srcs/sources_1/new/lfsr.v
  Z:/timing_game/timing_game.srcs/sources_1/new/7seg.v
  Z:/timing_game/timing_game.srcs/sources_1/new/frame.v
  Z:/timing_game/timing_game.srcs/sources_1/new/main.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc Z:/timing_game/timing_game.srcs/constrs_1/new/main.xdc
set_property used_in_implementation false [get_files Z:/timing_game/timing_game.srcs/constrs_1/new/main.xdc]


synth_design -top m_main -part xc7a100tcsg324-1 -directive AreaOptimized_high -control_set_opt_threshold 1


write_checkpoint -force -noxdef m_main.dcp

catch { report_utilization -file m_main_utilization_synth.rpt -pb m_main_utilization_synth.pb }
