# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Z:/demo/demo.cache/wt [current_project]
set_property parent.project_path Z:/demo/demo.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo z:/demo/demo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  Z:/game_palette.mem
  Z:/game.mem
}
read_verilog -library xil_defaultlib {
  Z:/demo/demo.srcs/sources_1/new/main.v
  Z:/demo/demo.srcs/sources_1/new/lfsr.v
}
read_ip -quiet Z:/demo/demo.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all z:/demo/demo.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/demo/demo.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all z:/demo/demo.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files Z:/demo/demo.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc Z:/demo/demo.srcs/constrs_1/new/main.xdc
set_property used_in_implementation false [get_files Z:/demo/demo.srcs/constrs_1/new/main.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top m_main -part xc7a100tcsg324-1


write_checkpoint -force -noxdef m_main.dcp

catch { report_utilization -file m_main_utilization_synth.rpt -pb m_main_utilization_synth.pb }
